services:
  # Dolibarr
  dolibarr:
    image: tuxgasy/dolibarr:14.0.2
    container_name: dolibarr
    ports:
      - "8080:80"
    environment:
      - DOLI_URL_ROOT=http://localhost:8080
      - DOLI_DB_HOST=dolibarr-mariadb
      - DOLI_DB_USER=epitech
      - DOLI_DB_PASSWORD=epitech13
      - DOLI_DB_NAME=dolibarr
    links:
      - dolibarr-mariadb
#password admin admin
  # MariaDB
  dolibarr-mariadb:
    image: mariadb:10.8
    container_name: dolibarr-mariadb
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./dolibarr:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=epitech13
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=epitech
      - MYSQL_PASSWORD=epitech13

volumes:
  data:
