name: Code formatting

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install clang format
        run: |
          sudo apt-get install --no-install-recommends -qqy clang-format
      - name: Check actual code formatting
        run: |
          git ls-files | grep -v simulation-client/rlImGui/ | grep -v simulation-client/imgui/ | grep -e '\.cpp$' -e '\.hpp$' -e '\.c$' -e '\.h$' | xargs clang-format -i
          git diff --exit-code
